# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30b35a0b22af6e77dde25b12233cca6278710c1baf2364f25e4d5af3724cb522ee14fb344c7774d4cba447da148676f247896edf7397c31f15380a3ec4b8e83f

test:
  secret_key_base: 0dba40a9cc68311a1b79b6dda5d38aaf67f5305d019ed942c3f2f05cb1dbbc0ee992fa88ff5f77a8fbc3a38b336b8445fd22436fb9724d11f0a8919f6ec33c10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
